server {
    listen 8081;
    server_name 192.168.0.236;
    location / {
        proxy_pass http://127.0.0.1:5666;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \;
        proxy_set_header Connection upgrade;
        proxy_set_header Host \System.Management.Automation.Internal.Host.InternalHost;
    }
}
